spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: message
          uri: lb://message
          predicates:
            - Path=/message
        - id: web
          uri: lb://main
          predicates:
            - Path=/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
server:
  port: 9000

