version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db-continent:
    image: postgres:12
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
  rabbitmq:
    image: rabbitmq:3.9
    container_name: rabbitmq
    ports:
      - "61613:61613"
      - "15672:15672"
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
  grafana:
    image: grafana/grafana:8.5.21
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: monitoring-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"

  promtail:
    image: grafana/promtail:main
    container_name: monitoring-promtail
    volumes:
      - ./promtail/promtail-docker-config.yaml:/etc/promtail/docker-config.yaml
      - ../logs/:/var/log/

    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:main
    container_name: monitoring-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"