spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  endpoints:
    web:
      exposure:
        include: liquibase, health, prometheus
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true